### PR TITLE
#164691174 Setup React Router DOM 

### PR DESCRIPTION
**Pull request by NicholusMuwonge**
#### What does this PR do?
- allows usage of routes to switch to different pages.
- allow homepage to be rendered using route ```http://localhost:8080/``` 
- allow login page to be rendered via route ```http://localhost:8080/login```
- add fall back not found page in case route isnt found
#### Description of Task to be completed?
- adding configuration to the webpack.config file to allow the file path for creating builds to be defined and found on the server running.
- adding components like Home and login to be rendered on different login routes.
#### How should this be manually tested?
- clone this repo and run ``` npm install``` for dependencies.
- run ```npm start``` in your terminal or ```http://localhost:8080/``` and your response should be;
Screenshot 2019-07-03 at 11 17 53

- you can click login link on the page for a redirect or type ```http://localhost:8080/login``` into your browser and you should see
Screenshot 2019-07-03 at 11 21 16

#### What are the relevant pivotal tracker stories?
[#164691174](https://www.pivotaltracker.com/story/show/164691174)

### CODE REVIEW

**Review by richien — CHANGES_REQUESTED** [review]
Hi @NicholusMuwonge, this is good progress however I have noted some linting errors on this PR when I run `npm start` as in the screenshot below - 
image
Kindly run the command `npm run lint` on your local branch to check that there are no linting errors before pushing the code up.

**Review by frankopkusianwar — COMMENTED** [review]
great work @NicholusMuwonge, the functionality works as described. kindly work on @richien feedback and I will approve

**Comment by NicholusMuwonge** [comment]
> Hi @NicholusMuwonge, this is good progress however I have noted some linting errors on this PR when I run `npm start` as in the screenshot below -
> image
> Kindly run the command `npm run lint` on your local branch to check that there are no linting errors before pushing the code up.

Hey @richien, your recommendations are fantastic and I have implemented them. thanks

**Comment by richien** [comment]
> > Hi @NicholusMuwonge, this is good progress however I have noted some linting errors on this PR when I run `npm start` as in the screenshot below -
> > image
> > Kindly run the command `npm run lint` on your local branch to check that there are no linting errors before pushing the code up.
> 
> Hey @richien, your recommendations are fantastic and I have implemented them. thanks

Thanks for implementing the feedback, this is ok now. Great work!

**Review by richien — APPROVED** [review]

**Review by sebbss — APPROVED** [review]

**Review by frankopkusianwar — APPROVED** [review]

**Pull request closed without merging**
