### PR TITLE
#166880075 Users should be able to Login to Authors Haven

### PR DESCRIPTION
**Pull request by richien**
#### What does this PR do?

- Adds login functionality to the application

#### Description of Task to be completed?

- Add login form, email input, and password input components.
- Pick data from the login form and make a request to the `ah-backend-API` to log in a user.
- Redirect the user to the `articles` page upon successful login or display an error in case it fails

#### How should this be manually tested?

- Go to the [sign in](https://ah-frontend-space-stagin-pr-15.herokuapp.com/signin) page 
- Enter your email and password in the fields then enter 
- If your account is valid, you will be redirected to the `articles` page
NOTE: A registered account is required to access this route - you can register with the API on this [link](https://ah-haven-space.herokuapp.com/#api-users-create). Ensure to use a valid email address

#### What are the relevant pivotal tracker stories?

[#166880075](https://www.pivotaltracker.com/story/show/166880075)

#### Screenshots (if appropriate)

image

### CODE REVIEW

**Review by NicholusMuwonge — CHANGES_REQUESTED** [review]
Hey @richien, your work is impressive but I would pray you get your page more responsive and then also work to get the code climate to stop complaining

**Comment by richien** [comment]
> Hey @richien, your work is impressive but I would pray you get your page more responsive and then also work to get the code climate to stop complaining

Thank you for the feedback @NicholusMuwonge, both of these are being resolved presently.

**Review by NicholusMuwonge — APPROVED** [review]
Looks good to me

**Review by sebbss — APPROVED** [review]
LGTM

**Comment by NicholusMuwonge** [comment]
Kindly change the navbar sign in and signup content to something like maybe `profile | signout` or you could have a profile containing everything when the login is successful. Thank you.

**Review by frankopkusianwar — COMMENTED** [review]
nice work @richien, kindly ensure to display appropriate links in the navbar after redirecting the user. I.e it should not show login and signup links. 
navbar
currently your navbar appears like this.

**Review by frankopkusianwar — COMMENTED** [review]
@richien kindly ensure to cover all the lines that are not covered with tests in the coverage report
coverag

**Comment by richien** [comment]
> @richien kindly ensure to cover all the lines that are not covered with tests in the coverage report
> coverag

@frankopkusianwar, thank you for the feedback. This has been resolved

**Review by frankopkusianwar — APPROVED** [review]

**Pull request merged**
