### PR TITLE
#167565588 Ability to read comments

### PR DESCRIPTION
**Pull request by NicholusMuwonge**
#### What does this PR do?
- Allows users to  be able to read the various comments that are attached to an article
- Allows users to be alerted if there are no comments for a particular article.

#### Description of Task to be completed?
- returns comments for a particular article
- returns an alert that no comments found if a particular article doesn't have comments.
- tests the comments components, container, and reducers.

#### How should this be manually tested?
- clone this repository
- npm install and npm run dev
- run this https://ah-frontend-space-stagin-pr-26.herokuapp.com/ and move down to 
Screenshot 2019-07-31 at 10 41 12

Alternatively, one can check out this article that has comments already 
https://ah-frontend-space-stagin-pr-26.herokuapp.com/how-to-train-your-puppy-wsdsd-7/

- Go back to the main page, choose a slug from the browser
- Create a new comment.
- return to that comment in the browser and refresh
- one should be able to see the created comments

#### What are the relevant pivotal tracker stories?
[#167565588](https://www.pivotaltracker.com/story/show/167565588)

#### Screenshots
Screenshot 2019-07-31 at 10 50 24
Screenshot 2019-07-31 at 10 50 44

### CODE REVIEW

**Review by richien — COMMENTED** [review]
Nice work @NicholusMuwonge, I was able to see some comments displayed. Also, the UI looks nice and clean though I couldn't help but wish there was some more information in the comment header in addition to the user name, such as the time the comment was created. Good work with the designs

**Review by richien — APPROVED** [review]

**Review by MuhanguziDavid — COMMENTED** [review]
Nice work @NicholusMuwonge , please add timestamps to the comments

**Comment by NicholusMuwonge** [comment]
> Nice work @NicholusMuwonge, I was able to see some comments displayed. Also, the UI looks nice and clean though I couldn't help but wish there was some more information in the comment header in addition to the user name, such as the time the comment was created. Good work with the designs

I have added time stamps, please

**Review by MuhanguziDavid — APPROVED** [review]
LGTM

**Pull request merged**
