### PR TITLE
#166880074 Enable users to reset their passwords.

### PR DESCRIPTION
**Pull request by richien**
#### What does this PR do?

 - Implements the password-reset functionality

#### Description of Task to be completed?

- Add a page on which to verify that a user is registered
- Call the endpoint that sends a password reset link to the user's
  email address after verification of the user's email address
- Add a page that the user is redirected to in order to enter a
  new password

#### How should this be manually tested?

- On the [sign in](https://ah-frontend-space-stagin-pr-20.herokuapp.com/signin) page, click the `forgot password?` link
- You will be redirected to the `confirm email` page where you will enter a registered email address.
- If successful, you will receive a password reset link in your email.
- Click the link to be redirected to the password reset page.
- Enter your new password twice to reset your password.

#### What are the relevant pivotal tracker stories?

[#166880074](https://www.pivotaltracker.com/story/show/166880074)

#### Screenshots (if appropriate)

Screenshot 2019-07-20 at 17 36 28

Screenshot 2019-07-20 at 17 39 39

### CODE REVIEW

**Comment by NicholusMuwonge** [comment]
@richien, I have tested it out but the link sent to my email didn't redirect me back to the password reset page.

**Comment by richien** [comment]
> @richien, I have tested it out but the link sent to my email didn't redirect me back to the password reset page.

Please share the link that was shared with you

**Comment by NicholusMuwonge** [comment]
I think the

> > @richien, I have tested it out but the link sent to my email didn't redirect me back to the password reset page.
> 
> Please share the link that was shared with you

I think the link works fine, kindly wait on my full review as I go through  the rest of your code

**Review by sebbss — APPROVED** [review]
this looks good to me thanks for this implementation @richien

**Review by frankopkusianwar — APPROVED** [review]
LGTM

**Review by MuhanguziDavid — COMMENTED** [review]
Nice work with the password reset @richien . Please ensure that a user is redirected to the login page when they reset a password.

**Review by MuhanguziDavid — COMMENTED** [review]
I also keep getting this toast after I reset a password. What could be causing it!?

Screenshot 2019-07-22 at 10 54 42

**Comment by richien** [comment]
> I also keep getting this toast after I reset a password. What could be causing it!?
> 
> Screenshot 2019-07-22 at 10 54 42

This has to do with the Social Auth feature - the domain that was configured on Google and Facebook for the callback url is `https://ah-frontend-space-staging.herokuapp.com` and not `https://ah-frontend-space-stagin-pr-20.herokuapp.com`. Therefore, whenever a request goes out to google, this error response is returned . 
image
image

My expectation is that this issue is specific to the review app for the reasons stated above

**Comment by MuhanguziDavid** [comment]
@richien , I was running the app locally. Didn't use the review app.

**Comment by richien** [comment]
> @richien , I was running the app locally. Didn't use the review app.

Are you able to login using google on your local app?
I dont get this issue on a local instance, only on the review app and it is directly related to the SocialAuth funtionality, specifically Google. Kindly confirm that your local instance is actually able to complete a login via social auth

**Review by MuhanguziDavid — APPROVED** [review]
LGTM!!!

**Pull request merged**
