### PR TITLE
#166880078 Users should be able to create an article

### PR DESCRIPTION
**Pull request by sebbss**
#### What does this PR do?

- Enable a user to create an article

#### Description of Task to be completed?

- add actions that make API calls to the backend to post an article
- add reducers that change state whenever actions are dispatched
- create a form for creating articles

#### How should this be manually tested?

- login into the deployed application 
- navigate to create an article
- enter details concerning the article
- press submit to create the article 

#### What are the relevant pivotal tracker stories?

[#166880078](https://www.pivotaltracker.com/story/show/166880078)

### CODE REVIEW

**Review by NicholusMuwonge — CHANGES_REQUESTED** [review]
Please kindly update the tests to get code climate to stop complaining otherwise nice work

**Comment by sebbss** [comment]
> Please kindly update the tests to get code climate to stop complaining otherwise nice work

I have fixed the code climate issues

**Review by richien — CHANGES_REQUESTED** [review]
Awesome work @sebbss, I was able to create an article and upload an image. Speaking of uploading an image, it would be nice if you added a progress bar to the image upload field so that a user can get feedback that an upload is going on. Currently, nothing happens when the upload button is clicked and yet the image is actually uploaded. Other than that, great job

**Review by NicholusMuwonge — CHANGES_REQUESTED** [review]
Please kindly protect the route otherwise nice work

**Review by richien — APPROVED** [review]

**Review by NicholusMuwonge — APPROVED** [review]
nice work @sebbss

**Review by MuhanguziDavid — APPROVED** [review]
LGTM

**Pull request merged**
