### PR TITLE
#166880066 Setup an empty react project

### PR DESCRIPTION
**Pull request by richien**
#### What does this PR do?

Sets up an empty react project with support for linting using Airbnb.

#### Description of Task to be completed?

- add  src and public directories and initialize a package.json file
- install and configure Webpack
- install and configure babel
- install react and react-dom
- install and initialize ESlint to use Airbnb style guides

#### How should this be manually tested?

- Clone this repo and switch to this branch
- `cd` into the root of the project directory and run `npm install` to install the packages
  in the package.json file.
-  Run `npm start` to open up the browser with an instance of a development server.
#### What are the relevant pivotal tracker stories?

[#166880066](https://www.pivotaltracker.com/story/show/166880066)

#### Screenshots (if appropriate)

image

### CODE REVIEW

**Review by frankopkusianwar — COMMENTED** [review]
great work @richien however, I am getting an error of `webpack-dev-server: command not found` when I try to run npm start. could I be missing something. Please clarify on this and also icase of any installations we have to make before running the application


Screen Shot 2019-07-01 at 19 56 25

**Comment by richien** [comment]
> great work @richien however, I am getting an error of `webpack-dev-server: command not found` when I try to run npm start. could I be missing something. Please clarify on this and also icase of any installations we have to make before running the application
> 
> Screen Shot 2019-07-01 at 19 56 25

Hi @frankopkusianwar, thank you for the feedback. I have added instructions for how to install the packages to the PR. You will need to run `npm install` before `npm start`. Please let me know if that resolves the above issue you raised.

**Comment by frankopkusianwar** [comment]
> > great work @richien however, I am getting an error of `webpack-dev-server: command not found` when I try to run npm start. could I be missing something. Please clarify on this and also icase of any installations we have to make before running the application
> > Screen Shot 2019-07-01 at 19 56 25
> 
> Hi @frankopkusianwar, thank you for the feedback. I have added instructions for how to install the packages to the PR. You will need to run `npm install` before `npm start`. Please let me know if that resolves the above issue you raised.

Thanks @richien the issue has been resolved

**Comment by frankopkusianwar** [comment]
@richien also kindly checkout the branch the PR is pointing to. this is showing master, please ensure that it points to develop

Thank you for catching that, my mistake. This has been rectified.

**Review by frankopkusianwar — APPROVED** [review]

**Review by sebbss — APPROVED** [review]
good work @richien this looks good to me

**Review by NicholusMuwonge — APPROVED** [review]
Beautiful work brother, I see the file structure was well thought of and even locally, it all works as expected.

**Pull request closed without merging**
